name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
      
      - name: Set up Python3 🔧
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry 🔧
        run: pip3 install poetry

      - name: Check Syntax
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  